### PR TITLE
Preloader

### PR DESCRIPTION
**Pull request by WonderCRM**
Preloader + css

### CODE REVIEW

**Comment by WonderCRM** [comment]
Corrected ru translation a little.

`const Tr = JSON.parse(
          '{"en":{"layouts.set":"Layouts of the page are saved on device","layouts.home.add":"Element added to home page","layouts.home.remove":"Element removed from home page","menu.sidebar.home":"Home","menu.navbar.home":"Home","menu.sidebar.printerstats":"Heat and fan","menu.navbar.printerstats":"Heat and fan","menu.sidebar.movements":"Movements","menu.navbar.movements":"Movements","menu.sidebar.printing":"Printing","menu.navbar.printing":"Printing","menu.sidebar.stream":"Video","menu.navbar.stream":"Video","menu.sidebar.storage":"Storage","menu.navbar.storage":"Storage","menu.sidebar.daily":"Daily chart","menu.navbar.daily":"Daily chart","menu.sidebar.monthly":"Monthly chart","menu.navbar.monthly":"Monthly chart","menu.sidebar.configuration":"Configuration","menu.navbar.configuration":"Configuration","menu.sidebar.introduction":"Introduction","menu.navbar.introduction":"Introduction","date.label":"Date","chart.no_data":"No data","chart.no_production":"No production","chart.loading":"Loading...","chart.temperature.title":"Temperatures","chart.temperature.subtitle":"Extruders and Bed temperatures","chart.temperature.T0.label":"Primary extruder","chart.temperature.T1.label":"Secondary extruder","chart.temperature.B.label":"Bed","chart.production.battery.title":"Battery","informative.realtime.move.title":"Printer movement","informative.realtime.T0Temp.title":"Extruder 1","informative.realtime.T1Temp.title":"Extruder 2","informative.realtime.fan.title":"Fan speed","informative.realtime.fan.button_set":"Set Fan speed","informative.realtime.fan.text":"Last fan speed ","informative.temperature.T0Temp.title":"Extruder 1","informative.temperature.T1Temp.title":"Extruder 2","informative.realtime.bed.title":"Bed temp","informative.realtime.status.title":"Printer status","informative.realtime.status.button.resume":"Resume","informative.realtime.status.button.pause":"Pause","informative.realtime.status.button.stop":"Stop","informative.realtime.status.label.file":"File","informative.realtime.status.label.size":"Size","informative.realtime.status.label.elapsed_time":"Elapsed time","informative.realtime.video.title":"Video","informative.realtime.video.subtitle":"Video stream of the printer","last.update":"Last update","upload.success":"File {filename} was uploaded!","upload.failure":"File {filename} upload error! ({err})","box.file.upload.title":"File upload","box.file.upload.choose_file":"Choose file","box.file.upload.upload_and_print":"Upload and print","box.file.upload.upload":"Upload","box.file.upload.dialog.text":"File already exist, continue? A progressive will be added at the end of the file. And this file will always be used.","box.file.upload.subtitle":"Add file to the 3D printer SD","box.gcode.title":"GCode sender","box.gcode.subtitle":"Write on editor and send","box.gcode.send":"Send","box.gcode.placeholder":"Insert your gcode here","box.gcode.message.sended":"{numGcodeLine} GCode commands sended!","table.file.list.title":"File list","table.file.list.subtitle":"All files inside sd card","configuration.preferences.title":"Settings","configuration.preferences.subtitle":"Generic settings","configuration.preferences.update":"Update preferences","configuration.network.title":"Network configuration","configuration.network.subtitle":"Remember to set a correct static IP","configuration.network.staticIP.label":"Select a static IP","configuration.email.table.email":"EMail","configuration.email.notification.enabled.label":"Activate notification when printer finish job","configuration.network.update":"Update network settings","configuration.camera.title":"Camera configuration","configuration.camera.subtitle":"Use an esp32-cam like in the article","configuration.camera.streamingurl.label":"esp32-cam IP","configuration.camera.update":"Update camera configuration","configuration.camera.rotation.label":"Camera rotation","configuration.email.notification.title":"Notification settings","configuration.email.notification.finishprintemail.label":"Email for notification of finish print","configuration.email.notification.subtitle":"Configure Server SMTP first","configuration.email.notification.add":"New notification email","configuration.email.notification.add.modal.title":"Insert","configuration.email.notification.add.modal.no_email":"None","configuration.email.notification.add.modal.first_alarm":"First alarm","configuration.email.notification.add.modal.all_state_change":"At all state change","configuration.save.success":"Configuration saved successfully","configuration.save.failed":"Failed to save configuration <br>{err}","configuration.smtpserver.title":"Settings server SMTP","configuration.smtpserver.subtitle":"To receive notification you need configure SMTP server","configuration.smtpserver.update":"Update data of server SMTP","home.fab.tooltip":"Locally save current layouts of this page","page.intro":"<div><h2>Introduction</h2><div>To install this Web App activate the chrome features <b> Desktop PWAs</b></div><div>Copy this link and paste in your browser</div><div>chrome://flags/#enable-desktop-pwas</div></div>","websocket.open":"3D Printer connected","websocket.close":"3D Printer disconnected","websocket.error":"Error <br>Not connected!","websocket.message.preheat.sended":"Command pre heat for toot {tool} ad temp {preHeatTemp} sended!","websocket.message.preheat.button":"Pre-Heat","iframe.button.move":"Drag to move","iframe.button.close":"Click to close"},"it":{"layouts.set":"Il layout è stato salvato sul dispositivo","layouts.home.add":"Elemento aggiunto alla home page","layouts.home.remove":"Elemento rimosso dalla home page","menu.sidebar.home":"Home","menu.navbar.home":"Home","menu.sidebar.printerstats":"Calore e ventola","menu.navbar.printerstats":"Calore e ventola","menu.sidebar.storage":"Memoria","menu.navbar.storage":"Memoria","menu.sidebar.printing":"Stampa","menu.navbar.printing":"Stampa","menu.sidebar.movements":"Movimenti","menu.navbar.movements":"Movimenti","menu.sidebar.monthly":"Grafici mensili","menu.navbar.monthly":"Grafici mensili","menu.sidebar.stream":"Video","menu.navbar.stream":"Video","menu.sidebar.configuration":"Configurazione","menu.navbar.configuration":"Configurazione","menu.sidebar.introduction":"Introduzione","menu.navbar.introduction":"Introduzione","date.label":"Data","chart.no_data":"Nessun dato","chart.no_production":"Nessuna produzione","chart.loading":"Caricamento","chart.temperature.T0.label":"Estrusore principale","chart.temperature.T1.label":"Estrusore secondario","chart.temperature.B.label":"Bed","chart.production.battery.title":"Batteria","chart.temperature.title":"Temperature","chart.temperature.subtitle":"Temperature Estrusori e Bed","informative.realtime.move.title":"Movimenti stampante","informative.realtime.video.title":"Video","informative.realtime.video.subtitle":"Streaming video della stampante","informative.realtime.fan.title":"Velocità ventola","informative.realtime.fan.button_set":"Imposta velocità","informative.temperature.T0Temp.title":"Estrusore 1","informative.temperature.T1Temp.title":"Estrusore 2","informative.realtime.bed.title":"Temperatura bed","informative.realtime.status.title":"Stato stampante","informative.realtime.status.button.resume":"Riavvia","informative.realtime.status.button.pause":"Pausa","informative.realtime.status.button.stop":"Stop","informative.realtime.status.label.file":"File","informative.realtime.status.label.size":"Dimensione","informative.realtime.status.label.elapsed_time":"Tempo trascorso","informative.realtime.T0Temp.title":"Estrusore 1","informative.realtime.T1Temp.title":"Estrusore 2","last.update":"Ultimo agg.","upload.success":"Il file {filename} caricato!","upload.failure":"Il file {filename} errore di upload! ({err})","box.file.upload.upload_and_print":"Carica e stampa","box.file.upload.upload":"Carica","box.file.upload.choose_file":"Seleziona file","box.file.upload.title":"Caricamento file","box.file.upload.subtitle":"Aggiungi un file all\'SD della stampante","box.file.upload.dialog.text":"Il file esiste già, continuare? Verrà apposto un progressivo al termine del file. E sarà usato sempre questo file.","box.gcode.title":"Invio GCode","box.gcode.subtitle":"Scrivi ed invia","box.gcode.send":"Invio","box.gcode.placeholder":"Inserisci il tuo gcode qui","box.gcode.message.sended":"Inviati {numGcodeLine} comandi GCode!","table.file.list.title":"Lista file","table.file.list.subtitle":"Tutti i file dell\'SD Card","configuration.preferences.title":"Preferenze","configuration.preferences.subtitle":"Preferenze generiche","configuration.preferences.update":"Aggiorna preferenze","configuration.network.title":"Configurazione di rete","configuration.network.subtitle":"Ricorda di impostare un indirizzo IP statico","configuration.network.staticIP.label":"Seleziona un IP statico","configuration.email.notification.enabled.label":"Attiva notifiche al completamento stampa","configuration.email.table.email":"EMail","configuration.email.table.name":"Nome","configuration.network.update":"Aggiorna dati rete","configuration.camera.title":"Configurazione camera","configuration.camera.subtitle":"Usa un esp32-cam modificato come da articolo","configuration.camera.streamingurl.label":"IP dell\'esp32-cam","configuration.camera.update":"Aggiorna dati camera","configuration.camera.rotation.label":"Rotazione camera","configuration.email.notification.title":"Impostazioni di notifica","configuration.email.notification.finishprintemail.label":"Email per notifica completamento job","configuration.email.notification.subtitle":"Configura il server SMTP prima","configuration.email.notification.add":"Aggiungi email per notifiche","configuration.email.notification.add.modal.title":"Inserisci","configuration.save.success":"Configurazione salvata correttamente","configuration.save.failed":"Errore al salvataggio configurazione {br}{err}","configuration.smtpserver.title":"Impostazioni server SMTP","configuration.smtpserver.subtitle":"Per ricevere qualsiasi tipo di notifica è necessario configurare il server SMTP","configuration.smtpserver.update":"Aggiorna i dati del server SMTP","home.fab.tooltip":"Salva localmente i layouts di questa pagina","page.intro":"<div><h2>Introduzione</h2><div>Per installare questa WebApp è necessario abilitare questa features di Chrome <b> Desktop PWAs</b></div><div>Copia incolla questo link sul browser </div><div>chrome://flags/#enable-desktop-pwas</div></div>","websocket.message.preheat.sended":"Il comando di preriscaldamento del {tool} alla temperatura {preHeatTemp} mandato!","websocket.message.preheat.button":"Pre-Riscaldamento","websocket.open":"Stampante connessa","websocket.close":"Stampante disconnessa","websocket.error":"Errore <br>Impossibile stabilire una connessione","iframe.button.move":"Trascina per muovere","iframe.button.close":"Clicca per chiudere"},"ru":{"layouts.set":"Макет страницы сохраняются на устройстве","layouts.home.add":"Элемент добавлен на главную страницу","layouts.home.remove":"Элемент удален с домашней страницы","menu.sidebar.home":"Главная","menu.navbar.home":"FLYING BEAR GHOST 5","menu.sidebar.printerstats":"Температура и охлаждение","menu.navbar.printerstats":"Температура и охлаждение","menu.sidebar.movements":"Движение","menu.navbar.movements":"Движение","menu.sidebar.printing":"Печать","menu.navbar.printing":"Печать","menu.sidebar.stream":"Видео","menu.navbar.stream":"Видео","menu.sidebar.storage":"SD карта","menu.navbar.storage":"SD карта","menu.sidebar.daily":"График по дням","menu.navbar.daily":"График по дням","menu.sidebar.monthly":"График помесячно","menu.navbar.monthly":"График помесячно","menu.sidebar.configuration":"Конфигурация","menu.navbar.configuration":"Конфигурация","menu.sidebar.introduction":"Вступление","menu.navbar.introduction":"Вступление","date.label":"Дата","chart.no_data":"Нет данных","chart.no_production":"No production","chart.loading":"Загрузка...","chart.temperature.title":"Температура","chart.temperature.subtitle":"Температура экструдера и стола","chart.temperature.T0.label":"Экструдер 1","chart.temperature.T1.label":"Экструдер 2","chart.temperature.B.label":"Стол","chart.production.battery.title":"Аккумулятор","informative.realtime.move.title":"Движение принтера","informative.realtime.T0Temp.title":"Экструдер 1","informative.realtime.T1Temp.title":"Экструдер 2","informative.realtime.fan.title":"Скорость вентилятора","informative.realtime.fan.button_set":"Установка скорости вентилятора","informative.temperature.T0Temp.title":"Экструдер 1","informative.temperature.T1Temp.title":"Экструдер 2","informative.realtime.bed.title":"Температура стола","informative.realtime.status.title":"Статус принтера","informative.realtime.status.button.resume":"Продолжить","informative.realtime.status.button.pause":"Пауза","informative.realtime.status.button.stop":"Стоп","informative.realtime.status.label.file":"Файл","informative.realtime.status.label.size":"Размер","informative.realtime.status.label.elapsed_time":"Время от старта","informative.realtime.video.title":"Видео","informative.realtime.video.subtitle":"Видеопоток принтера","last.update":"Обновлено","upload.success":"Файл {filename} загружен!","upload.failure":"Файл {filename} ошибка загрузки! ({err})","box.file.upload.title":"File upload","box.file.upload.choose_file":"Выберите файл","box.file.upload.upload_and_print":"Загрузить и напечатать","box.file.upload.upload":"Upload","box.file.upload.dialog.text":"File already exist, continue? A progressive will be added at the end of the file. And this file will always be used.","box.file.upload.subtitle":"Добавить файл на SD-карту 3D-принтера","box.gcode.title":"Отправитель GCode","box.gcode.subtitle":"Напишите и отправьте","box.gcode.send":"Отправлять","box.gcode.placeholder":"Вставьте сюда свой gcode","box.gcode.message.sended":"Отправлено {numGcodeLine} команд GCode!","table.file.list.title":"Список файлов","table.file.list.subtitle":"Все файлы на SD-карте","configuration.preferences.title":"Конфигурация","configuration.preferences.subtitle":"Основные настройки","configuration.preferences.update":"Сохранить настройки","configuration.network.title":"Конфигурация сети","configuration.network.subtitle":"Remember to set a correct static IP","configuration.network.staticIP.label":"Использовать статический IP","configuration.email.table.email":"EMail","configuration.email.notification.enabled.label":"Активировать уведомление, когда принтер завершит печать","configuration.network.update":"Сохранить настройки сети","configuration.camera.title":"Настройки камеры","configuration.camera.subtitle":"Используйте камеру esp32, как в статье.","configuration.camera.streamingurl.label":"esp32-cam IP","configuration.camera.update":"Сохранить настройки камеры","configuration.camera.rotation.label":"Вращение камеры","configuration.email.notification.title":"Notification settings","configuration.email.notification.finishprintemail.label":"Email для уведомления о завершении печати","configuration.email.notification.subtitle":"Configure Server SMTP first","configuration.email.notification.add":"Email для уведомлений","configuration.email.notification.add.modal.title":"Вставить","configuration.email.notification.add.modal.no_email":"Нет","configuration.email.notification.add.modal.first_alarm":"Только первое исзменение состояния","configuration.email.notification.add.modal.all_state_change":"Любое изменение состояния","configuration.save.success":"Конфигурация сохранена","configuration.save.failed":"Ошибка сохранения конфигурации <br>{err}","configuration.smtpserver.title":"Конфигурация SMTP сервера","configuration.smtpserver.subtitle":"Для получения уведомлений вам необходимо настроить SMTP-сервер","configuration.smtpserver.update":"Обновить данные сервера SMTP","home.fab.tooltip":"Сохранить локально текущий макет страницы","page.intro":"<div><h2>Introduction</h2><div>To install this Web App activate the chrome features <b> Desktop PWAs</b></div><div>Copy this link and paste in your browser</div><div>chrome://flags/#enable-desktop-pwas</div></div>","websocket.open":"3D принтер подключен","websocket.close":"3D принтер отключен","websocket.error":"Ошибка <br>Нет соединения!","websocket.message.preheat.sended":"Команда преднагрева для {tool} на температуру {preHeatTemp} отправлена!","websocket.message.preheat.button":"Преднагрев","iframe.button.move":"Перетаскивать","iframe.button.close":"Нажмите, чтобы закрыть"}}'
        );`

**Comment by xreef** [comment]
Hi WonderCMR,
I add plain traslation file on resources, can you change that please?
Thanks Renzo

**Comment by WonderCRM** [comment]
> I add plain traslation file on resources, can you change that please?

Ok

**Comment by xreef** [comment]
Thanks Renzo

**Pull request merged**
